project:
  type: website
  output-dir: docs
  resources:
    - CNAME
    - .nojekyll
    - "Incorporating AI into Teaching.pdf" 
    - iita2025.pdf 
    - claude-dcf-example.xlsx

  render:
    - index.qmd

website:
  title: "Gen AI for Finance"
  site-url: https://finance-with-ai.org
  description: "Teaching the use of generative AI in finance"
  navbar:
    title: false
    search: true
    left:
      - icon: house-door-fill
        href: https://genai4finance.kerryback.com
        target: _blank
    right:
      - text: Blog
        href: https://blog.kerryback.com
        target: _blank
      - text: Spring 2025 Course
        href: https://mgmt675-2025.kerryback.com
        target: _blank
      - text: Spring 2026 Course
        href: https://mgmt675-2026.kerryback.com
        target: _blank
      - text: FMA Tutorial
        href: fma2025.pdf
        target: _blank
      - text: FMA IITA
        href: iita2025.pdf
        target: _blank
      - text: Python Workshop
        href: https://workshop.kerryback.com
        target: _blank

format:
  html:
    theme:
      light: flatly
      dark: superhero
    css: styles.css
    toc: true

comments:
  giscus:
    repo: kerryback/finance-and-ai
    repo-id: R_kgDOPrZjmA
    category: General
    category-id: DIC_kwDOPrZjmM4CvItR
    mapping: pathname
    reactions-enabled: true
    loading: lazy
    input-position: bottom
    theme: preferred_color_scheme 
