project:
  type: website
  output-dir: docs
  resources:
    - CNAME
    - .nojekyll

website:
  title: "Gen AI for Finance"
  site-url: https://finance-with-ai.org
  description: "Teaching the use of generative AI in finance"
  navbar:
    title: false
    search: true
    left:
      - icon: house-door-fill
        href: https://finance-with-ai.org
    right:
      - text: Blog
        href: https://blog.kerryback.com
        target: _blank
      - text: Syllabus
        href: https://mgmt675-2026.kerryback.com/MGMT675.pdf
        target: _blank
      - text: Discussions
        href: "#giscus"
      - text: FMA Tutorial
        href: https://fma2025.kerryback.com
        target: _blank
      - text: FMA Award
        href: "#"

format:
  html:
    theme:
      light: flatly
      dark: superhero
    css: styles.css
    toc: true

comments:
  giscus:
    repo: kerryback/finance-and-ai
    repo-id: R_kgDOPrZjmA
    category: General
    category-id: DIC_kwDOPrZjmM4CvItR
    mapping: pathname
    reactions-enabled: true
    loading: lazy
    input-position: bottom
    theme: preferred_color_scheme 
